# Generated by Django 2.0.2 on 2018-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daumnews',
            name='link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navernews',
            name='link',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
