# Generated by Django 2.0.2 on 2018-04-20 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newsselectmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DaumNews',
            new_name='Daum',
        ),
        migrations.RenameModel(
            old_name='NaverNews',
            new_name='Naver',
        ),
        migrations.AlterField(
            model_name='newsselectmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
