# Generated by Django 2.0.2 on 2018-04-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180420_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstitle',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
