# Generated by Django 2.0.2 on 2018-04-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180424_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsselectmodel',
            name='chosun',
            field=models.BooleanField(default=True),
        ),
    ]
