# Generated by Django 2.0.2 on 2018-04-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_newsselectmodel_chosun'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsselectmodel',
            name='joongang',
            field=models.BooleanField(default=True, verbose_name='중앙일보'),
        ),
        migrations.AlterField(
            model_name='newsselectmodel',
            name='chosun',
            field=models.BooleanField(default=True, verbose_name='조선일보'),
        ),
    ]
