# Generated by Django 2.0.2 on 2018-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_newsselectmodel_hani'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsselectmodel',
            name='ohmy',
            field=models.BooleanField(default=True, verbose_name='오마이뉴스'),
        ),
    ]
