# Generated by Django 2.0.2 on 2018-04-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_newsselectmodel_ohmy'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsselectmodel',
            name='khan',
            field=models.BooleanField(default=True, verbose_name='경향신문'),
        ),
    ]
