# Generated by Django 2.0.2 on 2018-05-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_newsselectmodel_kbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsselectmodel',
            name='sbs',
            field=models.BooleanField(default=True, verbose_name='sbs'),
        ),
    ]
