# Generated by Django 2.0.2 on 2018-05-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_newsselectmodel_mbc'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstitle',
            name='version',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
