# Generated by Django 2.0.2 on 2018-05-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_newstitle_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstitle',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
    ]
