# Generated by Django 2.0.2 on 2018-05-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180507_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstitle',
            name='version',
            field=models.BigIntegerField(),
        ),
    ]
